### ISSUE TITLE
Build errors when appending build data to the version string

### ISSUE THREAD

**Issue by tinnightcap** [nubisproject/nubis-builder#160]
When building an ami with build data in the version string, nubis-builder spits out a bunch of errors.

Example version string from nubis-skel project.json file:
"project_version": "v1.2.0_{{env `GIT_COMMIT_SHA`}}",

Errors from nubis-builder:
./nubis-builder/bin/nubis-builder: line 394: ${_AMI_FILE}: ambiguous redirect
./nubis-builder/bin/nubis-builder: line 401: ${_AMI_FILE}: ambiguous redirect
./nubis-builder/bin/nubis-builder: line 405: ${_AMI_FILE}: ambiguous redirect
./nubis-builder/bin/nubis-builder: line 405: ${_AMI_FILE}: ambiguous redirect
./nubis-builder/bin/nubis-builder: line 424: ${_AMI_FILE}: ambiguous redirect
./nubis-builder/bin/nubis-builder: line 401: ${_AMI_FILE}: ambiguous redirect
./nubis-builder/bin/nubis-builder: line 405: ${_AMI_FILE}: ambiguous redirect
./nubis-builder/bin/nubis-builder: line 405: ${_AMI_FILE}: ambiguous redirect
./nubis-builder/bin/nubis-builder: line 426: ${_AMI_FILE}: ambiguous redirect

**Comment by gozer** [comment]
Not an issue anymore
