### ISSUE TITLE
Intermittent build failure : Package ec2-ami-tools is not available

### ISSUE THREAD

**Issue by gozer** [Nubisproject/nubis-builder#29]
Base builds intermittently fail with this error from apt-land:

Package ec2-ami-tools is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ec2-ami-tools' has no installation candidate

**Comment by bhourigan** [comment]
Seems like an upstream repo issue and not a nubis-builder problem. Happens to me occasionally and I just retry building, and eventually it works. Please reopen if you think there is a bug in the tool.
