### ISSUE TITLE
Intermittently, packer fails with Error launching source instance: The security group 'sg-xxxxxx' does not exist in VPC 'vpc-yyyyyy'

### ISSUE THREAD

**Issue by gozer** [Nubisproject/nubis-builder#42]
1427830336,,ui,error,Build 'amazon-ebs-ubuntu' errored: Error launching source instance: The security group 'sg-37f1c952' does not exist in VPC 'vpc-2603a943' (InvalidGroup.NotFound)

**Comment by bhourigan** [comment]
Looking in the console I see VPC ID vpc-2603a943 is labeled as the default VPC in the sandbox, but when I try to look up sg-37f1c952 I don't see a SG with that ID.

**Comment by davecurado** [comment]
vpc-2603a943 is the default VPC, but we don't use the default VPC

**Comment by bhourigan** [comment]
Going to close this issue - please feel to reopen if more information can be provided.
