### ISSUE TITLE
Support acl tokens for nubis-consul command

### ISSUE THREAD

**Issue by limed** [nubisproject/nubis-builder#80]
nubis-consul currently just assumes you can post to a KV store without a token, since we now support acl tokens in consul the nubis-consul program will need to be able to support it as well

**Comment by limed** [comment]
Fixed this in PR #86 but should really fix it with a `--token` command line arg, currently doing this via environment variable which is not ideal

**Comment by gozer** [comment]
We deprecated nubis-consul
