### ISSUE TITLE
Should use https for consul URL

### ISSUE THREAD

**Issue by limed** [Nubisproject/nubis-builder#81]
If we are going to support sending secrets to consul using ACL tokens we need to be able to use https instead

https://github.com/Nubisproject/nubis-builder/blob/master/bin/nubis-consul#L81
https://github.com/Nubisproject/nubis-builder/blob/master/bin/nubis-consul#L123

**Comment by gozer** [comment]
Good point! Keeping in mind that in the CI case, communication to Consul happens via the local agent.

Might need to initially skip certificate validation, since we use self-signed certs at the moment 

Still important for the developer/sandbox case.

**Comment by gozer** [comment]
Done.
