### ISSUE TITLE
Make project_version automatically update if there is a version colision

### ISSUE THREAD

**Issue by tinnightcap** [Nubisproject/nubis-builder#9]
Currently if there is a newer version it generates an error like:

Version collision detected! nubis-dpaste already has a published AMI at 0.73, and we're trying to build 0.71. Please edit /tmp/builder.json.N65jE65n and bump the version to 0.74 or higher.

It would be nice if it could update the version automatically and generate a note or warning instead of an error.

**Comment by bhourigan** [comment]
Good call. I went ahead and changed the behavior of the two existing version control toggles in 62b77bd. A few different behaviors are now possible:

automatic_version_bump=1 automatic_version_verify=1
It will set the version to $latest + 1, always. Drawback is it won't let you set it more than $latest +1.

automatic_version_bump=0 automatic_version_verify=1
Project version is left alone, but nubis-builder will check and be sure that an AMI doesn't already exist

automatic_version_bump=1 automatic_version_verify=0
Version tracks builds numbers, but no effort is made to ensure that the version is unique.

automatic_version_bump=0 automatic_version_verify=0
Don't fuss over the project version, and just build.

If you have the cycles I'd like a r? over the logic/flow.

**Comment by tinnightcap** [comment]
This makes sense to me and fixes the issue. The only thing is you might want to take your comment and add it to the readme for the benefit of others.

Thanks for addressing this.

**Comment by bhourigan** [comment]
Created https://github.com/Nubisproject/nubis-builder/issues/16 to track documentation requirements.
