### ISSUE TITLE
masterless puppet provisioner doesn't guarantee a clean slate

### ISSUE THREAD

**Issue by bhourigan** [nubisproject/nubis-builder#94]
I spent more time than I'd like to admit debugging an odd problem with the nubis_eip module:

```
    amazon-ebs-amazon-linux: Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class nubis_eip::eip at /tmp/packer-puppet-masterless/manifests/init.pp:5 on node ip-172-31-13-158.us-west-2.compute.internal
```

I noticed the timestamp was a few days old"

```
-rw-r--r-- 1 ec2-user ec2-user 589 Aug 31 03:33 packer-puppet-masterless/module-0/nubis_eip/manifests/eip.pp
```

After further evaluation it looks like /tmp/packer-puppet-masterless was left over from the most recent base build. I'm not sure whether this is a bug, or a feature. I'm leaning towards a bug since some files from a earlier version were left over and caused some confusion.

I'd propose something along the following to address this should a clean slate be desirable:

``` diff
diff --git a/packer/provisioners/librarian-puppet-masterless.json b/packer/provisioners/librarian-puppet-masterless.json
index 458f63a..e471e54 100644
--- a/packer/provisioners/librarian-puppet-masterless.json
+++ b/packer/provisioners/librarian-puppet-masterless.json
@@ -7,6 +7,11 @@
     "order": "0"
   },
   {
+    "type": "shell",
+    "inline": "rm -rf /tmp/packer-puppet-masterless",
+    "order": "9"
+  },
+  {
     "type": "puppet-masterless",
     "manifest_dir": "nubis/puppet",
     "manifest_file": "nubis/puppet/init.pp",
```

**Comment by gozer** [comment]
Done and implemented:

https://github.com/nubisproject/nubis-base/blob/develop/nubis/puppet/files/housekeeper#L14
